//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApnaPages
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060002
			public const int businessNames = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int locations_array = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int shareDialogList = 2131099648;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int orange = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_black = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_blue_matte = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_green_matte = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_orange_matte = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_pink_matte = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_red_matte = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_star_big_on_selected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ButtonStates = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int call_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int favorite = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int gradient = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int greybackground = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int greygrainy = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int home = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int OrangeButtonStates = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rightarrow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int spinner_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int spinnernormal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int spinnerpressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int spinnerSelector = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splash = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int suitecase = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sym_action_call = 2130837527;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int Click2Call = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int LinearLayout01 = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int autoCompleteTextView = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int btnAddToFavorites = 2131230733;
			
			// aapt resource value: 0x7f080014
			public const int btnCall = 2131230740;
			
			// aapt resource value: 0x7f080004
			public const int btnDirectory = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int btnFavorite = 2131230725;
			
			// aapt resource value: 0x7f08001b
			public const int btnFind = 2131230747;
			
			// aapt resource value: 0x7f080003
			public const int btnHome = 2131230723;
			
			// aapt resource value: 0x7f080017
			public const int btnMap = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int btnSMS = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int btnShare = 2131230744;
			
			// aapt resource value: 0x7f08000a
			public const int imageItem = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout1 = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int linearLayout2 = 2131230734;
			
			// aapt resource value: 0x7f080016
			public const int linearLayout3 = 2131230742;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout4 = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int linearText = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int listView = 2131230721;
			
			// aapt resource value: 0x7f08001a
			public const int spinner = 2131230746;
			
			// aapt resource value: 0x7f080011
			public const int textAddress = 2131230737;
			
			// aapt resource value: 0x7f080008
			public const int textBottom = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int textCity = 2131230738;
			
			// aapt resource value: 0x7f08000c
			public const int textName = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int textPhone = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int textTop = 2131230727;
			
			// aapt resource value: 0x7f080013
			public const int textWebsite = 2131230739;
			
			// aapt resource value: 0x7f080000
			public const int widget28 = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AutoComplete_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int categoryList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int categoryListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int details = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int directoryList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int directoryListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000f
			public const int Add = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int AddToFavorites = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int ApnaPages = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int Call = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int Del = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int Directory = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Favorite = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int Find = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int Home = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int Location = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int Map = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int SMS = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Share = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int shareByCancel = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int shareByEmail = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int shareBySMS = 2131034123;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ButtonText = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ButtonTextSmall = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MenuButtonText = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			private Style()
			{
			}
		}
	}
}
